/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple_gradle_java;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("Hello world!");
    	System.out.println("PR validation automation");
        return true;
    }
}
